[package]
name = "radio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.4"
soapysdr = "0.3.1"
num-complex = "0.4"
anyhow = "1.0.69"
log = "0.4.17"
threadpool = "1.8.1"
